name: $PREFIX$SUFFIX

services:
  mysql:
    container_name: $PREFIX-mysql$SUFFIX
    image: $PREFIX/mysql:latest
    build: ./docker-images/mysql
    restart: ${SERVICES_RESTART:-no}
    ports:
      - ${PORT_MYSQL:-3306}:3306
    volumes:
      - ./docker-images/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ${VOLUME_MYSQL}
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-pass}
      MYSQL_DATABASE: ${DB_DATABASE-$PREFIX}
      MYSQL_USER: ${DB_USERNAME-$PREFIX}
      MYSQL_PASSWORD: ${DB_PASSWORD-pass}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  node:
    container_name: $PREFIX-node$SUFFIX
    image: $PREFIX/build:latest
    build: ./docker-images/node
    restart: no
    volumes:
      - ./:/app
    environment:
      TZ: ${TZ:-UTC}
